<?php
/**
 * This file comes from the "Digital License Manager" WordPress plugin.
 * https://darkog.com/p/digital-license-manager/
 *
 * Copyright (C) 2020-2024  Darko Gjorgjijoski. All Rights Reserved.
 * Copyright (C) 2020-2024  IDEOLOGIX MEDIA DOOEL. All Rights Reserved.
 *
 * Digital License Manager is free software; you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * Digital License Manager program is distributed in the hope that it
 * will be useful,but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License v3
 * along with this program;
 *
 * If not, see: https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * Code written, maintained by Darko Gjorgjijoski (https://darkog.com)
 */

use IdeoLogix\DigitalLicenseManager\Utils\SanitizeHelper;

defined( 'ABSPATH' ) || exit;
/* @var \IdeoLogix\DigitalLicenseManager\Abstracts\AbstractTool $tool */
/* @var \IdeoLogix\DigitalLicenseManager\Abstracts\AbstractToolMigrator[] $plugins */
?>

<h3><?php esc_html_e( 'Add Order Item Licenses', 'digital-license-manager' ); ?></h3>
<p><?php echo wp_kses( sprintf(__('Version 1.7.1 introduces %s meta key for every order line item that contains License generated from that order. This is not as widely used now in the Digital License Manager\'s source code, expect for handling refunds, however it will be in the future.', 'digital-license-manager'), '<strong>_dlm_license_id</strong>'), SanitizeHelper::ksesAllowedHtmlTags()  ); ?></p>
<p><?php echo wp_kses( sprintf(__('We recommend running this tool to assign the %s meta data for every historical order line item that contains License generated by Digital License Manager.', 'digital-license-manager'), '<strong>_dlm_license_id</strong>'), SanitizeHelper::ksesAllowedHtmlTags()  ); ?></p>
<p><?php echo wp_kses( sprintf(__('If you used Digital License Manager before the version 1.7.1 we strongly recommend to run this tool, otherwise no action is required.', 'digital-license-manager'), '<strong>_dlm_license_id</strong>'), SanitizeHelper::ksesAllowedHtmlTags()  ); ?></p>
<p><?php esc_html_e( 'The tool should be used only once! No need to repat the feature multiple times.', 'digital-license-manager' ); ?></p>
<form class="dlm-tool-form" method="POST" action="">
    <div class="dlm-tool-form-row dlm-tool-form-row-progress" style="display: none;">
        <div class="dlm-tool-progress-bar">
            <p class="dlm-tool-progress-bar-inner">&nbsp;</p>
        </div>
        <div class="dlm-tool-progress-info"><?php esc_html_e( 'Initializing...', 'digital-license-manager' ); ?></div>
    </div>
    <div class="dlm-tool-form-row">
        <input type="hidden" name="id" value="<?php echo esc_attr( $tool->getId() ); ?>"/>
        <input type="hidden" name="identifier" value=""/>
        <input type="hidden" name="tool" value="<?php echo esc_attr( $tool->getSlug() ); ?>">
        <button type="submit" class="button button-small button-primary"><?php esc_html_e( 'Process', 'digital-license-manager' ); ?></button>
    </div>
</form>